name: Sync to GitHub Release Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync to github-release branch
        run: |
          # Fetch all branches
          git fetch origin

          # Check if github-release branch exists
          if git show-ref --verify --quiet refs/remotes/origin/github-release; then
            git checkout github-release
            git merge main --no-edit
          else
            # Create github-release branch if it doesn't exist
            git checkout -b github-release
          fi

          # Push to github-release branch
          git push origin github-release
